### ISSUE TITLE
/v2/shopping/hotel-offers endpoint bug

### ISSUE THREAD

**Issue by csar2651** [amadeus4dev/amadeus-node#133]
## Description

const response = await amadeus.shopping.hotelOffers.get({citycode})

returns AuthorizationError, but access_token is valid.

other endpoints are working.

## Versions

v14.16.1

**Comment by minjikarin** [comment]
Hello, we have Hotel Search v3 released last year, but currently, the node SDK doesn't support the latest version. the code that you mentioned is linked with Hotel Search V2, and it requires manual access granted if you want to use V2. I encourage you to wait a bit more as we are currently working on releasing Hotel List API to be used with Hotel search V3. otherwise, please send an email to developers@amadeus.com with your email address (registered in the portal), so that we can grant access to you. :)
