### ISSUE TITLE
Add support for Hotel Booking API

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-node#41]

**Comment by anthonyroux** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SDK Node] Add Hotel Booking](https://trello.com/c/BFLz0TXu/123-sdk-node-add-hotel-booking)

**Comment by VehpuS** [comment]
Is the Amadeus self-service API for hotel booking finalized? The docs mention it being in beta

**Comment by akshitsingla** [comment]
Yes, @VehpuS. Check it out here - https://developers.amadeus.com/self-service/category/hotel/api-doc/hotel-booking.

**Comment by VehpuS** [comment]
Thanks @akshitsingla. If you'll look at the last line of the overview, the API is described as being in beta. 

I asked about it because it being in beta seemed to make sense considering the API seems to be asking to pass credit card information directly (according to the docs) which intuitively doesn't seem secure (but maybe I'm missing something).

**Comment by akshitsingla** [comment]
Hello @VehpuS ,
Thanks for raising this. Indeed, we're working on updating the API overview page to remove that last line.
Regarding the current status - It is no longer in beta, and available to everyone in both - Test & Production environments.
Regarding CC information - Some bookings require the CC info to be passed, hence the field. It is PCI-DSS compliant.

**Comment by VehpuS** [comment]
Thanks for the feedback :). If possible - I would really appreciate to see an explanation of how the booking flow is supposed to work from search to paying for the booking - and specifically how do I know when I need to send CC info to finalize a hotel booking?

**Comment by VehpuS** [comment]
I should mention, what is mainly unclear for me now is how to integrate payment by a customer in the process - is there a way to direct customers to pay in an Amadeus endpoint or is it mandatory to implement payment in our platform as part of the integration with the Amadeus booking API, and if so - at what stage and how is the payment by the customer done?

**Comment by akshitsingla** [comment]
Glad, I could help @VehpuS.

The booking flow goes in this order:
1. Hotel Search API: /shopping/hotel-offers/ endpoint (To search for a hotel in a preferred location)
2. Hotel Search API: /shopping/hotel-offers/by-hotel endpoint (To search for different offers in the preferred hotel)
3. Hotel Search API: /shopping/hotel-offers/{offer-id} (To re-confirm the price of the offer)
4. Hotel Booking API (To make the booking)

Regarding sending CC to finalize the booking: Look for the value for "policies.paymentType" inside a "hotel-offer" object. If it is any of 'guarantee', 'deposit', 'prepay' - then you need to send the "payments" object (includes CC details); otherwise if it is 'holdTime' - then you can skip sending it.

Regarding payments: For Hotel bookings, the payments are done directly at the hotel. The "payments" information (only CC supported for the moment) sent through this API, is used for one of the above mentioned purpose: 
- guarantee (The hotel charges only in case of no-show, or whenever their policy is validated)
- deposit (The hotel charges/blocks some amount)
- prepay (The hotel charges complete amount on the credit-card)
Note: The API only supported CC payments at this point.

I hope I could answer all your queries, but if not - please feel free to reach out to us at developers@amadeus.com for further clarifications.

Also, thanks a ton for your valuable feedback!

Stay safe, stay healthy! :)
