### ISSUE TITLE
FlightOrders POST - expects different payload

### ISSUE THREAD

**Issue by hatemalimam** [amadeus4dev/amadeus-node#97]
## Description
The creation of a flight order expects a different payload than the one documented. (`data` wrapper to the request object)

__Expected Behavior:__ [What you expect to happen]

```javascript
amadeus.booking.flightOrders.post(
      JSON.stringify({
         data: {
           'type': 'flight-order',
           'flightOffers': response.flightOffers,
           'travelers_info': []
         }
      })
```

or handle the `data` internally.

__Actual Behavior:__ [What actually happens]

```javascript
amadeus.booking.flightOrders.post(
      JSON.stringify({
        'type': 'flight-order',
        'flightOffers': response.flightOffers,
        'travelers_info': []
      })
```

Results an error: `MANDATORY DATA MISSING - data needed 400/32171`
## Versions

[What version of Node/NPM are you running? What Operating System are you on?]
v12.16.1
## Checklist

Please make sure you checked the following:

* Are you running any of the current [Node LTS versions](https://nodejs.org/en/about/releases/)? yes
* Did you download the latest version of this library? yes

Let me know if I can help with a PR.

Thank you.

**Comment by tsolakoua** [comment]
Hello @hatemalimam, we have a dedicated repository with self-contained [code examples](https://github.com/amadeus4dev/amadeus-code-examples) (it's mentioned in the README). In that repository you can see the [Node example for the Flight Create Orders API](https://github.com/amadeus4dev/amadeus-code-examples/blob/master/flight_create_orders/v1/post/Node%20SDK/flight_create_orders.js) (in conjunction with the Flight Offers Search and Flight Offers Price API). 

The purpose of the list of supported endpoints is to show the endpoints and signatures available in the SDK. That's why for APIs with long payloads, such us the Flight Create Orders and Hotel Booking we just show the structure of the body and instead offer the complete code in the examples repo.
